BE300_Actualizar_librerias-internas_python
Funread/funread pull request #311
Opened 2024-09-13 17:27 UTC by DarvinGuti13

Recopilación de las librerias internas utilizadas en el proyecto, actualizadas y probadas.

2024-09-18 10:00 UTC, raraya95 commented on funread_backend/requirements.txt
> +
@DarvinGuti13 veo que agregaste muchas más librerías de las que existían. La idea del ticket era actualizar las existentes a la última versión y probar que funcionara. Todas las nuevas librerías son necesarias?

2024-09-18 22:11 UTC, DarvinGuti13 commented on funread_backend/requirements.txt
> +
Buenas tardes @raraya95, me disculpo si tienes razón, fue un error de comando a la hora de enlistar las librerias del proyecto, ya lo corrigo y subo al drive el documento con las librerias del proyecto backend.

2024-09-19 00:18 UTC, raraya95 requested changes
https://github.com/Funread/funread/pull/311/files#r1764775238

2024-09-19 01:37 UTC, DarvinGuti13 commented
He realizado los cambios solicitados, por favor revisarn nuevamente. @raraya95 @Lenar-Tercero

2024-11-21 01:12 UTC, closed without merging