BE307_Corrección-agregar/eliminar-estudiante-de-grupo
Funread/funread pull request #313
Opened 2024-09-22 01:13 UTC by DeynerPR

Corrección de error al agregar estudiante a un grupo.

El error se debe a que el modelo StudentsGroups contiene una condición de combinación única de variables 'userid' y 'groupscreateid', con lo que no puede crearse otro registro con la misma combinación.

Entonces cuando la persona agrega  el estudiante el serialisador responde un True en una validación en el metodo add_new en el archivo views.py, entonces al ser true se crea el registro.

Pero cuando la persona elimina al estudiante del grupo, solo se modifica un atributo para que no se muestre más. No se borra realmente el registro.

Entonces cuando se se agrega nuevamente el estudiante al grupo, el serialisador devuelve un false cuando hace las validaciones, porque verifica que la combinación única existe en un registro en la tabla.  Eso retorna un false al método add_new en views.py y el método no crea el registro.

Para solucionarlo, hice un else después de la validación, donde verifica si el error es por la combinación única que indica que ya existe el registro, entonces en ves de crearlo, solo lo busca y lo actualiza, su parámetro isactive de 0 a 1 nuevamente, para que se muestre en el front end.

2024-10-01 17:13 UTC, FernandoSZM requested changes
Al agregar un estudiante a un grupo y luego eliminarlo la ventana muestra que se elimino con exito y el estudiante es APARENTEMENTE removido del grupo, pero en la base de datos se ve claramente que el estudiante sigue registrado en el grupo (lo pueden comprobar en la tabla studentgroup de la base de datos)

Como nota adicional a la hora de eliminar un estudiante de un grupo se deberia mostrar un mensaje de confirmacion (para el equipo de FE)

2024-10-02 00:34 UTC, DeynerPR commented
Hola Fernando efectivamente, cuando se elimina un estudiante de un grupo no se borra realmete de la base de datos.

 El cambio consistió en actualizar el registro cuando ya existe, ya que el error surgía cuando el registro ya existía y se trataba de crear nuevamnete.
 

No cambié la lógica a eliminar el registro para no cambiar la lógica implementada de no borrar el registro realmente de la base de datos.

2024-10-18 19:44 UTC, FernandoSZM approved these changes

2024-10-18 19:47 UTC, FernandoSZM commented
Perfecto, no entendia que se referia a un borrado logico, los cambios estan perfectos, al eliminar el estudiante del grupo el estado pasa a inactivo en la base de datos

2024-10-18 19:47 UTC, merged