BE324_Implementación_de_Endpoints_para_Gamificación_(UserLevels_UserPoints_UserPoints_Badges_UserBadge)
Funread/funread pull request #326
Opened 2024-10-29 04:49 UTC by DarvinGuti13

Sección 1: Puntos por Lectura o Creación de Contenidos
Implementado el sistema de puntos para recompensar a los usuarios por completar libros (100 puntos) y por crear nuevos libros (200 puntos).
La parte de canjear puntos por personalizaciones en la plataforma (destacada en amarillo) se considera para implementación futura y no se incluyó en este commit.

Sección 2: Insignias por Logros Específicos
Implementado el sistema de insignias, donde los usuarios reciben recompensas visuales y puntos adicionales por alcanzar ciertos hitos, como leer 10, 50 y 100 libros.

Sección 3: Tabla de Clasificación
Implementada la tabla de clasificación para mostrar a los 10 mejores usuarios mensuales basados en puntos acumulados.
La clasificación en divisiones (Plata, Oro, Platino y Diamante) no especifica los puntos requeridos para cada nivel, y esta parte está pendiente de ser definida.

2024-11-01 01:16 UTC, raraya95 requested changes
Por favor hacer merge de main al branch y arreglar los conflictos

2024-11-01 21:40 UTC, DarvinGuti13 commented
@raraya95 Listo, Resolucion de conflictos despues de hacr el merge del main, ignorar el segundo pull se me fue equivocado..

2024-11-01 23:33 UTC, oscararrietapineda approved these changes

2024-11-11 20:12 UTC, raraya95 requested changes
Favor revisar las recomendaciones en todas las entidades

2024-11-11 20:12 UTC, raraya95 commented on funread_backend/Badges/urls.py
> +    path('api/badges/list_user_badges_with_status/<int:user_id>/', views.list_user_badges_with_status)
Estas no son las mejores prácticas para crear endpoints (ver https://medium.com/@nadinCodeHat/rest-api-naming-conventions-and-best-practices-1c4e781eb6a5). No es necesarios agregar sufijos como crear, listar, actualizar, eliminar, el método que le asignamos al endpoint es el que nos va a decir la acción que se va a tomar.

El último ejemplo en la corrección hay que revisarlo.


```suggestion
urlpatterns = [
    path('api/badges/', views.create_badge),
    path('api/badges/', views.list_badges),
    path('api/badges/<int:badge_id>/', views.update_badge),
    path('api/badges/<int:badge_id>/', views.delete_badge),
    path('api/badges/user/<int:user_id>/', views.list_user_badges_with_status)
```

2024-11-11 20:12 UTC, raraya95 commented on funread_backend/Badges/views.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
Usemos negaciones para evitar nested statements
```suggestion
        if serializer.is_valid() == False:
           return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
             
        serializer.save()  # Guardar la nueva insignia en la base de datos
        return Response(serializer.data, status=status.HTTP_201_CREATED)
```

2024-11-11 20:12 UTC, raraya95 commented on funread_backend/Badges/views.py
> +        if serializer.is_valid():
Igual no las negaciones

2024-11-11 20:12 UTC, raraya95 commented on funread_backend/UserBadge/urls.py
> +]
Utilizar "-" para mejorar legibilidad. También aplicar las mejores prácticas listadas arriba.
```suggestion
urlpatterns = [
    path('api/user-badges/', views.award_badge_to_user),
    path('api/user-badges/user/<int:user_id>/', views.list_user_badges),
    path('api/user-badges/<int:user_badge_id>/', views.delete_user_badge),
     
]
```

2024-11-14 20:00 UTC, raraya95 requested changes

2024-11-14 20:00 UTC, raraya95 commented on funread_backend/UserBadge/urls.py
> +    path('api/user-badges/<int:user_id>/', views.list_user_badges),
```suggestion
    path('api/user-badges/user/<int:user_id>/', views.list_user_badges),
```

2024-11-14 20:00 UTC, raraya95 commented on funread_backend/UserPointsLog/urls.py
> +    path('api/User-PointsLog/<int:log_id>/', views.edit_user_points),
```suggestion
    path('api/user-points-log/award/reading', views.award_points_for_reading),
    path('api/user-points-log/award/book-cretion', views.award_points_for_creating_book),
    path('api/user-points-log/<int:user_id>/', views.get_user_points),
    path('api/user-points-log/<int:log_id>/', views.edit_user_points),
```

2024-11-14 20:00 UTC, raraya95 commented on funread_backend/funread_backend/urls.py
> +    path('User_Levels/',include('User_Levels.urls'))
Cambiar el nombre del folder también
```suggestion
    path('UserLevels/',include('UserLevels.urls'))
```

2024-11-14 20:00 UTC, raraya95 commented on funread_backend/.env
> +SETTINGS_DATABSE_PASSWORD='8946'
dejar el valor anterior

2024-11-22 02:02 UTC, raraya95 requested changes

2024-11-22 02:02 UTC, raraya95 commented on frontend/src/Components/Shared/ProfileStudent/data.js
> +    baseURL: 'http://127.0.0.1:8000', // Cambia esta URL según tu configuración
creo que en este caso tienes que usar el axiosAuth que otros componentes utilizan:
`axiosAuth().get(...)`

2024-11-22 04:49 UTC, DarvinGuti13 commented on frontend/src/Components/Shared/ProfileStudent/data.js
> +    baseURL: 'http://127.0.0.1:8000', // Cambia esta URL según tu configuración
Listo @raraya95, ese archivo data.js mas bien se me fue y se me olvido borrarlo no estaba haciendo nada, el archivo api que hace referencia a ese componente es Profile.js
![profilejs](https://github.com/user-attachments/assets/899ecd94-a38c-417a-9925-1de417f2ef21)

2024-11-22 18:19 UTC, raraya95 reviewed
Creo que este PR se puede cerrar (cancelar), no tiene cambios significativos

2025-02-13 02:17 UTC, merged